const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const rootDir = path.join(__dirname, '..');

test('Voicemail Audio Lifecycle: server.js wires /vm-audio endpoint with permissions & range streaming', () => {
    const serverCode = fs.readFileSync(path.join(rootDir, 'server.js'), 'utf8');

    // 1. Route definition & authentication
    assert.match(serverCode, /app\.get\('\/vm-audio\/:mailbox\/:file',\s*requireAuth/, 'must define GET /vm-audio/:mailbox/:file with requireAuth');

    // 2. Permission checks
    assert.match(serverCode, /voicemail-download/, 'must check voicemail-download permission');
    assert.match(serverCode, /voicemail-listen/, 'must check voicemail-listen permission');

    // 3. MIME types mapping
    assert.match(serverCode, /'audio\/wav'/, 'must support audio/wav');
    assert.match(serverCode, /'audio\/x-gsm'/, 'must support audio/x-gsm');
    assert.match(serverCode, /'audio\/mpeg'/, 'must support audio/mpeg');

    // 4. HTTP Range streaming support (HTTP 206)
    assert.match(serverCode, /req\.headers\.range/, 'must inspect Range header');
    assert.match(serverCode, /res\.writeHead\(206,/, 'must return HTTP 206 for byte-range streaming');
    assert.match(serverCode, /'Content-Range':\s*`bytes \$\{start\}-\$\{end\}\/\$\{stat\.size\}`/, 'must return Content-Range header');
});

test('Voicemail Metadata Parser: accurately extracts duration, callerid, and timestamp from Asterisk .txt sidecar', () => {
    const sampleTxt = `;
; Message details sidecar generated by Asterisk
;
[message]
origmailbox=101
context=macro-vm
macrocontext=
exten=s
priority=2
callerchan=PJSIP/102-00000001
callerid="John Doe" <102>
origdate=Mon Oct 05 03:30:15 PM EEST 2026
origtime=1791207015
category=
flag=
duration=18
`;

    // Parse sidecar text
    const meta = {};
    for (const line of sampleTxt.split('\n')) {
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith(';')) continue;
        const [k, ...v] = trimmed.split('=');
        if (k && v.length) {
            meta[k.trim()] = v.join('=').trim();
        }
    }

    assert.strictEqual(meta.origmailbox, '101', 'mailbox should match 101');
    assert.strictEqual(meta.callerid, '"John Doe" <102>', 'callerid should be extracted');
    assert.strictEqual(parseInt(meta.duration, 10), 18, 'duration should be 18 seconds');
    assert.strictEqual(meta.origtime, '1791207015', 'origtime timestamp should match');
});

test('Voicemail Audio Security: Path traversal protection rejects malicious directory traversal sequences', () => {
    const maliciousPaths = [
        '../../etc/passwd',
        '../../../etc/shadow',
        '../INBOX/../../etc/hosts',
        '../../../../var/log/asterisk/full'
    ];

    const vmRoot = '/var/spool/asterisk/voicemail/default';
    for (const mal of maliciousPaths) {
        const resolved = path.resolve(vmRoot, '101', 'INBOX', mal);
        const mailboxRoot = path.resolve(vmRoot, '101', 'INBOX');
        const isSafe = resolved.startsWith(mailboxRoot + path.sep);
        assert.strictEqual(isSafe, false, `Path "${mal}" must be caught as unsafe traversal`);
    }
});
