'use strict';

const fs = require('fs');
const path = require('path');
const { execFile } = require('child_process');

const ASTERISK_BIN = process.env.ASTERISK_BIN || '/usr/sbin/asterisk';
const ASTERISK_CONF_DIR = process.env.ASTERISK_CONF_DIR || '/etc/asterisk';

/**
 * Initialize federation database schema idempotently.
 */
async function initFederationDb(conn) {
    if (!conn) return;

    // 1. Singleton federation settings
    await conn.execute(`
        CREATE TABLE IF NOT EXISTS \`sokrat_federation_settings\` (
            \`id\` TINYINT PRIMARY KEY DEFAULT 1,
            \`local_site_code\` VARCHAR(10) NOT NULL DEFAULT '10',
            \`local_node_name\` VARCHAR(100) NOT NULL DEFAULT 'Main PBX',
            \`panel_role\` ENUM('local', 'central') NOT NULL DEFAULT 'local',
            \`created_at\` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            \`updated_at\` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
    `);
    await conn.execute(`
        INSERT IGNORE INTO \`sokrat_federation_settings\` (\`id\`, \`local_site_code\`, \`local_node_name\`, \`panel_role\`)
        VALUES (1, '10', 'Main PBX', 'local')
    `);

    // 2. Connected federation peers
    await conn.execute(`
        CREATE TABLE IF NOT EXISTS \`sokrat_federation_peers\` (
            \`id\` INT AUTO_INCREMENT PRIMARY KEY,
            \`node_name\` VARCHAR(100) NOT NULL,
            \`host\` VARCHAR(255) NOT NULL,
            \`site_code\` VARCHAR(10) NOT NULL UNIQUE,
            \`iax_port\` SMALLINT UNSIGNED NOT NULL DEFAULT 4569,
            \`iax_user_inbound\` VARCHAR(80) NOT NULL,
            \`iax_peer_outbound\` VARCHAR(80) NOT NULL,
            \`iax_secret_enc\` TEXT NOT NULL,
            \`api_base_url\` VARCHAR(255) NOT NULL,
            \`api_key_enc\` TEXT NOT NULL,
            \`tls_cert_fingerprint\` VARCHAR(128) DEFAULT NULL,
            \`allow_internal_dialing\` TINYINT(1) NOT NULL DEFAULT 1,
            \`allow_outbound_egress\` TINYINT(1) NOT NULL DEFAULT 1,
            \`status\` ENUM('online', 'offline', 'error', 'unreachable') NOT NULL DEFAULT 'offline',
            \`last_sync_at\` DATETIME DEFAULT NULL,
            \`created_at\` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            \`updated_at\` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
    `);

    // 3. Remote extensions synced from peers
    await conn.execute(`
        CREATE TABLE IF NOT EXISTS \`sokrat_federation_remote_extensions\` (
            \`id\` INT AUTO_INCREMENT PRIMARY KEY,
            \`peer_id\` INT NOT NULL,
            \`native_extension\` VARCHAR(20) NOT NULL,
            \`dial_alias\` VARCHAR(30) NOT NULL UNIQUE,
            \`display_name\` VARCHAR(100) NOT NULL,
            \`status\` ENUM('online', 'offline', 'ringing', 'in_call', 'unknown') NOT NULL DEFAULT 'unknown',
            \`last_seen_at\` DATETIME DEFAULT NULL,
            UNIQUE KEY \`idx_peer_ext\` (\`peer_id\`, \`native_extension\`),
            KEY \`idx_peer_id\` (\`peer_id\`),
            KEY \`idx_dial_alias\` (\`dial_alias\`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
    `);

    // 4. Remote dongles synced from peers
    await conn.execute(`
        CREATE TABLE IF NOT EXISTS \`sokrat_federation_remote_dongles\` (
            \`id\` INT AUTO_INCREMENT PRIMARY KEY,
            \`peer_id\` INT NOT NULL,
            \`dongle_name\` VARCHAR(50) NOT NULL,
            \`phone_number\` VARCHAR(50) DEFAULT NULL,
            \`provider\` VARCHAR(50) DEFAULT NULL,
            \`status\` VARCHAR(50) DEFAULT 'Unknown',
            UNIQUE KEY \`idx_peer_dongle\` (\`peer_id\`, \`dongle_name\`),
            KEY \`idx_peer_id\` (\`peer_id\`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
    `);

    // 5. Ensure dashboard_user_extensions supports peer_id
    try {
        await conn.execute('ALTER TABLE `dashboard_user_extensions` ADD COLUMN `peer_id` INT DEFAULT NULL');
    } catch (_) {}
    try {
        await conn.execute('ALTER TABLE `dashboard_user_extensions` ADD KEY `idx_peer_id` (`peer_id`)');
    } catch (_) {}
}

/**
 * Generate Asterisk IAX2 peer and user configuration content.
 */
function generateIaxConfig(peers, localSettings, decryptFn) {
    const lines = [
        '; ====================================================================',
        '; Sokrat IAX2 Multi-Server PBX Federation Configuration',
        '; Auto-generated by Sokrat VoIP - Do not edit manually',
        '; ====================================================================',
        ''
    ];

    const localSiteCode = (localSettings && localSettings.local_site_code) || '10';

    for (const peer of (peers || [])) {
        if (!peer.site_code) continue;
        const siteCode = String(peer.site_code).trim();
        const host = String(peer.host || '').trim();
        const port = Number(peer.iax_port) || 4569;
        const inboundUser = peer.iax_user_inbound || `fed_in_site${siteCode}`;
        const outboundPeer = peer.iax_peer_outbound || `fed_out_site${siteCode}`;
        const remoteExpectedInbound = `fed_in_site${localSiteCode}`;

        let secret = '';
        if (typeof decryptFn === 'function' && peer.iax_secret_enc) {
            secret = decryptFn(peer.iax_secret_enc) || '';
        } else if (peer.iax_secret) {
            secret = peer.iax_secret;
        }

        // 1. Inbound User (Incoming calls from remote peer)
        lines.push(`; --- Inbound User from Peer: ${peer.node_name || siteCode} (Site ${siteCode}) ---`);
        lines.push(`[${inboundUser}]`);
        lines.push(`type=user`);
        lines.push(`auth=md5`);
        if (secret) {
            lines.push(`secret=${secret}`);
        }
        lines.push(`context=from-federation-site${siteCode}`);
        if (host && host !== 'dynamic') {
            lines.push(`deny=0.0.0.0/0.0.0.0`);
            lines.push(`permit=${host}/255.255.255.255`);
        }
        lines.push(`requirecalltoken=yes`);
        lines.push(`encryption=aes128`);
        lines.push(`forceencryption=yes`);
        lines.push(`disallow=all`);
        lines.push(`allow=alaw`);
        lines.push(`allow=ulaw`);
        lines.push(``);

        // 2. Outbound Peer (Outgoing calls to remote peer)
        lines.push(`; --- Outbound Peer to: ${peer.node_name || siteCode} (Site ${siteCode}) ---`);
        lines.push(`[${outboundPeer}]`);
        lines.push(`type=peer`);
        lines.push(`host=${host}`);
        lines.push(`port=${port}`);
        lines.push(`username=${remoteExpectedInbound}`);
        lines.push(`auth=md5`);
        if (secret) {
            lines.push(`secret=${secret}`);
        }
        lines.push(`qualify=yes`);
        lines.push(`qualifyfreqok=10000`);
        lines.push(`qualifyfreqnotok=2000`);
        lines.push(`encryption=aes128`);
        lines.push(`forceencryption=yes`);
        lines.push(`disallow=all`);
        lines.push(`allow=alaw`);
        lines.push(`allow=ulaw`);
        lines.push(`trunk=no`);
        lines.push(``);
    }

    return lines.join('\n') + '\n';
}

/**
 * Generate Asterisk dialplan configuration for multi-server federation.
 */
function generateDialplanConfig(peers, localSettings, remoteExtensions) {
    const lines = [
        '; ====================================================================',
        '; Sokrat IAX2 Multi-Server Federation Dialplan Contexts',
        '; Auto-generated by Sokrat VoIP - Do not edit manually',
        '; ====================================================================',
        '',
        '[sokrat-federation-out]',
        '; Multi-server federation outbound dispatch (isolated to configured peer site prefixes)'
    ];

    const activePeers = (peers || []).filter(p => p && p.site_code);

    if (activePeers.length === 0) {
        lines.push('; No active federation peers configured');
    }

    // Dynamic isolated routing per site code
    for (const peer of activePeers) {
        const siteCode = String(peer.site_code).trim();
        const codeLen = siteCode.length;
        const prefixLen = codeLen + 1; // '9' + siteCode
        const patternSuffix = codeLen <= 2 ? 'XX.' : 'X.';

        if (Number(peer.allow_internal_dialing) !== 0) {
            lines.push(`; Route to Site ${siteCode} internal extensions (${siteCode}XXX -> peer_${siteCode})`);
            lines.push(`exten => _${siteCode}${patternSuffix},1,NoOp(=== Sokrat Federation Dispatch to Site ${siteCode}: \${EXTEN} ===)`);
            lines.push(`same => n,Set(FED_HOPS=\${IF($["\${IAXVAR(FED_HOPS)}" = ""]?0:\${IAXVAR(FED_HOPS)})})`);
            lines.push(`same => n,GotoIf($[\${FED_HOPS} >= 2]?loop_detected)`);
            lines.push(`same => n,Set(IAXVAR(FED_HOPS)=$[\${FED_HOPS} + 1])`);
            lines.push(`same => n,Set(IAXVAR(FED_CALLER)=\${IF($["\${IAXVAR(FED_CALLER)}" = ""]?\${CALLERID(num)}:\${IAXVAR(FED_CALLER)})})`);
            lines.push(`same => n,Goto(peer_${siteCode},\${EXTEN:${codeLen}},1)`);
            lines.push(`same => n(loop_detected),Verbose(1, [FEDERATION-LOOP-ABORT] Max hops exceeded for \${EXTEN} from \${CALLERID(num)})`);
            lines.push(`same => n,Playtones(congestion)`);
            lines.push(`same => n,Congestion(10)`);
            lines.push(`same => n,Hangup()`);
            lines.push(``);
        }

        if (Number(peer.allow_outbound_egress) !== 0) {
            lines.push(`; Route to Site ${siteCode} remote egress PSTN/Dongle (9${siteCode}XXX -> peer_${siteCode} egress)`);
            lines.push(`exten => _9${siteCode}.,1,NoOp(=== Sokrat Federation Remote Egress via Site ${siteCode}: \${EXTEN} ===)`);
            lines.push(`same => n,Set(FED_HOPS=\${IF($["\${IAXVAR(FED_HOPS)}" = ""]?0:\${IAXVAR(FED_HOPS)})})`);
            lines.push(`same => n,GotoIf($[\${FED_HOPS} >= 2]?loop_detected)`);
            lines.push(`same => n,Set(IAXVAR(FED_HOPS)=$[\${FED_HOPS} + 1])`);
            lines.push(`same => n,Set(IAXVAR(FED_CALLER)=\${IF($["\${IAXVAR(FED_CALLER)}" = ""]?\${CALLERID(num)}:\${IAXVAR(FED_CALLER)})})`);
            lines.push(`same => n,Goto(peer_${siteCode},OUT_\${EXTEN:${prefixLen}},1)`);
            lines.push(`same => n(loop_detected),Verbose(1, [FEDERATION-LOOP-ABORT] Max hops exceeded for \${EXTEN} from \${CALLERID(num)})`);
            lines.push(`same => n,Playtones(congestion)`);
            lines.push(`same => n,Congestion(10)`);
            lines.push(`same => n,Hangup()`);
            lines.push(``);
        }
    }

    // Per-Peer Outbound Routing Contexts & Inbound Handling Contexts
    for (const peer of activePeers) {
        const siteCode = String(peer.site_code).trim();
        const outboundPeer = peer.iax_peer_outbound || `fed_out_site${siteCode}`;

        // 1. Outbound context [peer_<siteCode>]
        lines.push(`[peer_${siteCode}]`);
        lines.push(`; Direct extension dialing (e.g. 101 -> IAX2/${outboundPeer}/101)`);
        lines.push(`exten => _X.,1,NoOp(--- Routing to Peer Site ${siteCode} Native Exten: \${EXTEN} ---)`);
        lines.push(`same => n,Gosub(sub-record-check,s,1(out,\${EXTEN},dontcare))`);
        lines.push(`same => n,Dial(IAX2/${outboundPeer}/\${EXTEN},45,Ttr)`);
        lines.push(`same => n,Hangup()`);
        lines.push(``);
        lines.push(`; Remote Egress PSTN/Dongle Dialing (e.g. OUT_01011111111 -> routes via Site ${siteCode} Outbound Routes)`);
        lines.push(`exten => _OUT_X.,1,NoOp(--- Remote Egress via Peer Site ${siteCode}: \${EXTEN:4} ---)`);
        lines.push(`same => n,Gosub(sub-record-check,s,1(out,\${EXTEN:4},dontcare))`);
        lines.push(`same => n,Set(IAXVAR(FED_EGRESS)=1)`);
        lines.push(`same => n,Dial(IAX2/${outboundPeer}/\${EXTEN},60,Ttr)`);
        lines.push(`same => n,Hangup()`);
        lines.push(``);

        // 2. Inbound handling context [from-federation-site<siteCode>]
        lines.push(`[from-federation-site${siteCode}]`);
        lines.push(`; Check if call is for remote egress (calls outbound-allroutes on this PBX)`);
        lines.push(`exten => _OUT_X.,1,NoOp(--- Inbound Federation Egress Request from Site ${siteCode}: \${EXTEN:4} ---)`);
        lines.push(`same => n,GotoIf($["\${DB(FEDERATION/PEER_${siteCode}_EGRESS_ALLOWED)}" != "1"]?reject_egress)`);
        lines.push(`same => n,Goto(outbound-allroutes,\${EXTEN:4},1)`);
        lines.push(`same => n(reject_egress),Verbose(1, [FED-EGRESS-DENIED] Peer ${siteCode} is not permitted to use local outbound routes)`);
        lines.push(`same => n,Congestion(5)`);
        lines.push(`same => n,Hangup()`);
        lines.push(``);
        lines.push(`; Standard Inbound Extension Dialing: dispatch into from-internal-additional (bypasses outbound federation loop)`);
        lines.push(`exten => _X.,1,NoOp(--- Inbound Federation Call from Site ${siteCode} to Local Exten: \${EXTEN} ---)`);
        lines.push(`same => n,Goto(from-internal-additional,\${EXTEN},1)`);
        lines.push(``);
    }

    return lines.join('\n') + '\n';
}

/**
 * Ensure the custom Asterisk config files include Sokrat federation configs.
 */
function ensureAsteriskIncludes() {
    const extCustomPath = path.join(ASTERISK_CONF_DIR, 'extensions_custom.conf');
    const iaxCustomPath = path.join(ASTERISK_CONF_DIR, 'iax_custom.conf');

    try {
        if (fs.existsSync(extCustomPath)) {
            let content = fs.readFileSync(extCustomPath, 'utf8');
            let modified = false;

            if (!content.includes('#include sokrat_federation.conf')) {
                content += '\n; Sokrat IAX2 Federation Custom Dialplan Contexts\n#include sokrat_federation.conf\n';
                modified = true;
            }

            // Ensure include => sokrat-federation-out is inside [from-internal-custom]
            if (content.includes('[from-internal-custom]') && !content.includes('include => sokrat-federation-out')) {
                content = content.replace(
                    '[from-internal-custom]',
                    '[from-internal-custom]\n; === Sokrat IAX2 VoIP Multi-Server Federation Outbound Hook ===\ninclude => sokrat-federation-out\n'
                );
                modified = true;
            }

            if (modified) {
                fs.writeFileSync(extCustomPath, content, 'utf8');
            }
        }
    } catch (err) {
        console.error('Error updating extensions_custom.conf for federation:', err.message);
    }

    try {
        if (fs.existsSync(iaxCustomPath)) {
            let content = fs.readFileSync(iaxCustomPath, 'utf8');
            if (!content.includes('#include sokrat_federation_iax.conf')) {
                content += '\n; Sokrat IAX2 Federation Inbound/Outbound Peer Definitions\n#include sokrat_federation_iax.conf\n';
                fs.writeFileSync(iaxCustomPath, content, 'utf8');
            }
        }
    } catch (err) {
        console.error('Error updating iax_custom.conf for federation:', err.message);
    }
}

/**
 * Synchronize database peers into Asterisk IAX and dialplan config files and reload Asterisk.
 */
async function syncFederationAsteriskConfig(pool, decryptFn, execFileFn = execFile) {
    if (!pool) return { success: false, error: 'Database pool not provided' };

    try {
        const [settingsRows] = await pool.query('SELECT * FROM `asterisk`.`sokrat_federation_settings` WHERE id = 1');
        const localSettings = (settingsRows && settingsRows[0]) || { local_site_code: '10', local_node_name: 'Main PBX', panel_role: 'local' };

        const [peers] = await pool.query('SELECT * FROM `asterisk`.`sokrat_federation_peers` ORDER BY site_code ASC');
        const [remoteExts] = await pool.query('SELECT * FROM `asterisk`.`sokrat_federation_remote_extensions` ORDER BY dial_alias ASC');

        const iaxConfContent = generateIaxConfig(peers, localSettings, decryptFn);
        const dialplanConfContent = generateDialplanConfig(peers, localSettings, remoteExts);

        const iaxConfPath = path.join(ASTERISK_CONF_DIR, 'sokrat_federation_iax.conf');
        const dialplanConfPath = path.join(ASTERISK_CONF_DIR, 'sokrat_federation.conf');

        fs.writeFileSync(iaxConfPath, iaxConfContent, 'utf8');
        fs.writeFileSync(dialplanConfPath, dialplanConfContent, 'utf8');

        try {
            fs.chmodSync(iaxConfPath, 0o644);
            fs.chmodSync(dialplanConfPath, 0o644);
        } catch (_) {}

        ensureAsteriskIncludes();

        // Update AstDB egress permissions
        for (const peer of (peers || [])) {
            if (!peer.site_code) continue;
            const siteCode = String(peer.site_code).trim();
            const allowed = Number(peer.allow_outbound_egress) !== 0 ? '1' : '0';
            execFileFn(ASTERISK_BIN, ['-rx', `database put FEDERATION PEER_${siteCode}_EGRESS_ALLOWED ${allowed}`], () => {});
        }
        // Maintain custom federation trunks in asterisk.trunks so they can be selected in Outbound Routes
        try {
            const activeSiteCodes = new Set();
            for (const peer of (peers || [])) {
                if (!peer.site_code) continue;
                const siteCode = String(peer.site_code).trim();
                activeSiteCodes.add(siteCode);
                const trunkName = `[Fed] ${peer.node_name || 'Site ' + siteCode} (#${siteCode})`;
                const channelId = `Local/9${siteCode}$OUTNUM$@sokrat-federation-out`;

                const [existingTrunk] = await pool.query(
                    "SELECT trunkid FROM `asterisk`.`trunks` WHERE channelid LIKE ?",
                    [`Local/9${siteCode}%`]
                );

                if (existingTrunk && existingTrunk.length > 0) {
                    await pool.query(
                        "UPDATE `asterisk`.`trunks` SET name = ?, tech = 'custom', disabled = 'off' WHERE trunkid = ?",
                        [trunkName, existingTrunk[0].trunkid]
                    );
                } else {
                    const [maxRows] = await pool.query(
                        'SELECT COALESCE(MAX(trunkid), 0) + 1 AS nextId FROM `asterisk`.`trunks`'
                    );
                    const nextTrunkId = Number(maxRows[0]?.nextId || 1);
                    await pool.query(
                        "INSERT INTO `asterisk`.`trunks` (trunkid, name, tech, outcid, keepcid, maxchans, failscript, dialoutprefix, channelid, usercontext, provider, disabled, `continue`) VALUES (?, ?, 'custom', '', 'off', '', '', '', ?, '', NULL, 'off', 'off')",
                        [nextTrunkId, trunkName, channelId]
                    );
                }
            }

            // Clean up removed federation trunks
            const [allFedTrunks] = await pool.query(
                "SELECT trunkid, channelid FROM `asterisk`.`trunks` WHERE channelid LIKE 'Local/9%@sokrat-federation-out'"
            );
            for (const ft of (allFedTrunks || [])) {
                const match = String(ft.channelid).match(/Local\/9([0-9]+)\$OUTNUM\$/);
                if (match && !activeSiteCodes.has(match[1])) {
                    await pool.query("DELETE FROM `asterisk`.`trunks` WHERE trunkid = ?", [ft.trunkid]);
                    await pool.query("DELETE FROM `asterisk`.`outbound_route_trunks` WHERE trunk_id = ?", [ft.trunkid]);
                }
            }
        } catch (trunkErr) {
            console.error('Error syncing federation custom trunks:', trunkErr.message);
        }
        // Trigger Asterisk IAX2 & Dialplan reload
        await new Promise((resolve) => {
            execFileFn(ASTERISK_BIN, ['-rx', 'iax2 reload && dialplan reload'], (err, stdout, stderr) => {
                if (err) {
                    console.error('Asterisk federation reload notice:', err.message);
                }
                resolve();
            });
        });

        return { success: true, peersCount: peers.length };
    } catch (err) {
        console.error('syncFederationAsteriskConfig error:', err);
        return { success: false, error: err.message };
    }
}

/**
 * Format remote dial alias for FreePBX dial string (e.g. Ring Groups, Queues, Follow-Me).
 */
function formatRemoteDestination(dialAlias) {
    if (!dialAlias) return '';
    const clean = String(dialAlias).trim();
    return clean.endsWith('#') ? clean : `${clean}#`;
}

module.exports = {
    initFederationDb,
    generateIaxConfig,
    generateDialplanConfig,
    ensureAsteriskIncludes,
    syncFederationAsteriskConfig,
    formatRemoteDestination
};
